apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-k8s-example
  labels:
    app.kubernetes.io/version: latest
    app.kubernetes.io/name: quarkus-k8s-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/version: latest
      app.kubernetes.io/name: quarkus-k8s-example
  template:
    metadata:
      labels:
        app.kubernetes.io/version: latest
        app.kubernetes.io/name: quarkus-k8s-example
    spec:
      containers:
          - name: quarkus-k8s-example
            image: quarkus-k8s-example:1.0
            imagePullPolicy: IfNotPresent
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
